### ISSUE TITLE
Petz import

### ISSUE THREAD

**Issue by varekai** [bossjinja/PKC#23]
link to old account, verify using old password, import petz (with old results/titles), prefixes.

**Comment by bossjinja** [comment]
Problem: what to do with petz that have parents that have not been imported yet?

**Comment by bossjinja** [comment]
Another problem: people importing petz with prefixes that haven't been imported yet.

**Comment by bossjinja** [comment]
Re: prefix import problem
I think we will need to import all the prefixes into the new system initially, but have them as "stubs" - so just the UNIQUE bit and a standard display (say, lowercase with a capital letter) and have them all be owned by PKCAdmin. Then when people authenticate against their old account they can choose to basically reclaim ownership of their prefixes (matching against the UNIQUE field), at which point they can set how it is to be displayed. Imported petz can choose from all the prefixes, but maybe no new petz can be registered with a prefix owned by PKCAdmin?

This will account for the case where a prolific older member will not be returning, but current members have many petz with that prefix.

Though I guess Lauren's prefixes have already been pruned....? What a pickle.

**Comment by bossjinja** [comment]
Port all petz as partials. Port all the data!
