### ISSUE TITLE
Petz Registration

### ISSUE THREAD

**Issue by varekai** [bossjinja/PKC#24]
http://petzkennelclub.co.uk/petz_register.php

-------- Added by Jinja ---------
Registration workflow spec: https://docs.google.com/document/d/1tk0BgYRiKyCYCY-xO2dkqXP3Vo7Cbl00x7rHdOB_KA0/edit?usp=sharing

- [ ] Register petz form
- [x] Showname previewer (js)
- [ ] Breedfiles populated based on breed (ajax)
- [ ] File uploading 2-3 files
- [ ] List all regs for current User divided by workflow status
- [ ] Registrar approval queue
- [ ] Displaying the reg
- [ ] Displaying the breed standard
- [ ] Reject with comment
- [ ] Approve
- [ ] Edit
- [ ] Transfer of Partial Regs

Workflow statuses: Partial, Submitted, Approved, Rejected, Complete

**Comment by bossjinja** [comment]
Registration workflow spec: https://docs.google.com/document/d/1tk0BgYRiKyCYCY-xO2dkqXP3Vo7Cbl00x7rHdOB_KA0/edit?usp=sharing

- [ ] Register petz form
-- [ ] Showname previewer (js)
-- [ ] Breedfiles populated based on breed (ajax)
-- [ ] File uploading 2-3 files
- [ ] List all regs for current User divided by workflow status
- [ ] Registrar approval queue
-- [ ] Displaying the reg
-- [ ] Displaying the breed standard
-- [ ] Reject with comment
-- [ ] Approve
-- [ ] Edit
- [ ] Transfer of Partial Regs

Workflow statuses: Partial, Submitted, Approved, Rejected, Complete
